name: .NET Core Build and Test

on:
  pull_request:
    branches: [ main, develop ]
      
env:
  DOTNET_VERSION: '5.0.x'
    
jobs:
  build-and-test:
    name: Build and Test Application
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    
    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v2

    - run: apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib
    - run: apk add libgdiplus --repository https://dl-3.alpinelinux.org/alpine/edge/testing/
        
    - name: Install dependencies
      run: dotnet restore 
      
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal 

