name: .NET Core Build and Test

on:
  pull_request:
    branches: [ main, develop ]
      
env:
  DOTNET_VERSION: '5.0.x'
    
jobs:
  build-and-test:
    name: Build and Test Application
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:5.0
    strategy:
      matrix: 
        test_project: ['TestQTests', 'TestQIntegrationTests']
    
    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v2
        
    - name: Install dependencies
      run: dotnet restore 
      
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore ${{ matrix.test_project }} /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger "trx;LogFileName=${{ matrix.test_project }}.trx" --results-directory "./TestResults-${{ matrix.test_project }}"

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-results-${{ matrix.test_project }}
        path: TestResults-${{ matrix.test_project }}
      if: ${{ always() }}