name: '.NET Core Build and Test'

on:
  pull_request:
    branches: [ main, develop ]
      
env:
  DOTNET_VERSION: '5.0.x'
    
jobs:
  build-and-test:
    name: Build and Test Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Install dependencies
      run: dotnet restore 
      
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --logger "trx;LogFileName=test-results.trx" --results-directory "TestResults"

